### ISSUE TITLE
Approval / tx demo not working

### ISSUE THREAD

**Issue by gabitoesmiapodo** [BootNodeDev/dAppBoosterLanding-v1#11]
**Describe the bug**

It could be a temporary issue or just a configuration problem, but still... When clicking on "approve" and later accepting the tx in Metamask the tx / toast just stays there and nothing happens.

**To Reproduce**

1. Scroll down to the Transaction Button demo.
2. Click on 'Approve'
3. Accept on MM / your wallet.
4. You'll see a "Transaction for calling..." toast after the tx is triggered. Nothing happens afterwards. Eventually MM will inform you that the tx has finished / token spending has been approved, but the app won't change its status.
5. If you refresh the page, the "approve" button shows up again, so the app won't reflect the approval even then.

**Screenshots**

![image](https://github.com/user-attachments/assets/ea2cf806-df00-45dd-bb3b-d1c59e1d9b6f)

**Additional context**

URL: https://dappbooster.dev/
Wallet: Metamask.

**Comment by nicosampler** [comment]
This is an issue with the RPC. We already configured one from alchemy.
